name: around_you
description: "The AR Social Discovery App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # AR & Location
  ar_flutter_plugin: ^0.7.3 # Check for latest version
  geolocator: ^11.0.0
  google_maps_flutter: ^2.5.3

  # UI & General Utilities
  flutter_svg: ^2.0.9
  image_picker: ^1.0.7
  glassmorphism: ^3.0.0 # For glassmorphic effects
  google_fonts: ^6.1.0
  go_router: ^13.2.0 # For navigation
  intl: ^0.19.0 # For date/time formatting

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
