name: around_you
description: "The AR Social Discovery App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Location & Maps
  geolocator: ^9.0.2 # Keep this version for compatibility
  google_maps_flutter: ^2.5.3
  permission_handler: ^11.3.1

  # UI & General Utilities
  flutter_svg: ^2.0.9
  image_picker: ^1.0.7
  camera: ^0.10.5+9 # For AR camera functionality
  glassmorphism: ^3.0.0 # For glassmorphic effects
  cloudinary_public: ^0.21.0 # For image uploads
  google_fonts: ^6.1.0
  go_router: ^13.2.0 # For navigation
  intl: ^0.19.0 # For date/time formatting
  shared_preferences: ^2.2.2 # For storing user preferences
  connectivity_plus: ^5.0.2 # For checking network connectivity

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0 # Updated to latest version
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true

  # Assets for AR 3D models and other resources
  assets:
    - assets/map_style.json
    - assets/models/
    - assets/thumbnails/
    - assets/models/photo_frame.glb
    - assets/models/video_frame.glb
    - assets/models/text_display.glb
    - assets/models/audio_player.glb

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
