// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSMxEQ2aPrMVkmk6FSXXwfj-iO8uhuEbk',
    appId: '1:315598092021:web:46150177973b1a101077bc',
    messagingSenderId: '315598092021',
    projectId: 'artrav',
    authDomain: 'artrav.firebaseapp.com',
    storageBucket: 'artrav.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSMxEQ2aPrMVkmk6FSXXwfj-iO8uhuEbk',
    appId: '1:315598092021:android:46150177973b1a101077bc',
    messagingSenderId: '315598092021',
    projectId: 'artrav',
    storageBucket: 'artrav.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSMxEQ2aPrMVkmk6FSXXwfj-iO8uhuEbk',
    appId: '1:315598092021:ios:46150177973b1a101077bc',
    messagingSenderId: '315598092021',
    projectId: 'artrav',
    storageBucket: 'artrav.firebasestorage.app',
    iosBundleId: 'com.example.aroundYou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSMxEQ2aPrMVkmk6FSXXwfj-iO8uhuEbk',
    appId: '1:315598092021:macos:46150177973b1a101077bc',
    messagingSenderId: '315598092021',
    projectId: 'artrav',
    storageBucket: 'artrav.firebasestorage.app',
    iosBundleId: 'com.example.aroundYou',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSMxEQ2aPrMVkmk6FSXXwfj-iO8uhuEbk',
    appId: '1:315598092021:windows:46150177973b1a101077bc',
    messagingSenderId: '315598092021',
    projectId: 'artrav',
    storageBucket: 'artrav.firebasestorage.app',
  );
} 